### ISSUE TITLE
SyntaxError: 'yield' inside async function

### ISSUE THREAD

**Issue by Meghdeep** [aohan237/asyncnsq#7]
>>> from asyncnsq import create_reader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/asyncnsq/__init__.py", line 6, in <module>
    from .consumer import NsqConsumer
  File "/usr/local/lib/python3.5/dist-packages/asyncnsq/consumer.py", line 106
    yield await self._queue.get()

**Comment by aohan237** [comment]
messages method is abandoned.  you should use wait_messages
```python
            for waiter in nsq_consumer.wait_messages():
                message = await waiter
                print(message.body)
                await message.fin()
```

**Comment by aohan237** [comment]
and this is special in 0.4.5

**Comment by aohan237** [comment]
in version 1.0.0 there is no consumer

**Comment by Meghdeep** [comment]
How does one create a consumer then ?

**Comment by aohan237** [comment]
if you use version 0.4.5 :  use like this
```python
loop = asyncio.get_event_loop()

async def go():
    try:
        nsq_consumer = await create_nsq_consumer(
            lookupd_http_addresses=[
                ('127.0.0.1', 4161)],
            max_in_flight=200)
        await nsq_consumer.subscribe('test_async_nsq', 'nsq')
        for waiter in nsq_consumer.wait_messages():
            message = await waiter
            print(message.body)
            await message.fin()
        nsq_consumer = await create_nsq_consumer(
            host=['tcp://127.0.0.1:4150'],
            max_in_flight=200)
        await nsq_consumer.subscribe('test_async_nsq', 'nsq')
        for waiter in nsq_consumer.wait_messages():
            message = await waiter
            print(message.body)
            await message.fin()
    except Exception as tmp:
        logger.exception(tmp)

loop.run_until_complete(go())
```

if you use version 1.0.0 ,then you can refer to the readme
