### ISSUE TITLE
Why the tornado.iostream.StreamClosedError: Stream is closed come up ?

### ISSUE THREAD

**Issue by Meghdeep** [aohan237/asyncnsq#8]
2018-11-30 15:52:09:ERROR:nsq.conn uncaught exception in data event
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nsq/conn.py", line 290, in _read_body
    self.trigger(event.DATA, conn=self, data=data)
  File "/usr/local/lib/python3.5/dist-packages/nsq/event.py", line 84, in trigger
    ev(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nsq/conn.py", line 503, in _on_data
    self.send(protocol.nop())
  File "/usr/local/lib/python3.5/dist-packages/nsq/conn.py", line 296, in send
    self.stream.write(self.encoder.encode(data))
  File "/usr/local/lib/python3.5/dist-packages/tornado/iostream.py", line 387, in write
    self._check_closed()
  File "/usr/local/lib/python3.5/dist-packages/tornado/iostream.py", line 925, in _check_closed
    raise StreamClosedError(real_error=self.error)
tornado.iostream.StreamClosedError: Stream is closed

My code has a long processing time. Should I use message.touch() ? Is that maybe why it's disconnecting ?

**Comment by aohan237** [comment]
can you show your code? how do you use it and which version?
